project:
  type: website

website:
  title: NCAA Men's March Madness
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-SU25/final-project-MattOsterhoudt#
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: https://docs.google.com/presentation/d/1OMgenjV1c3qEKUSkS8oIu3XjEukESmRf_I0kQZBuQQQ/edit?usp=sharing
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
